### ISSUE TITLE
Plugin will not run

### ISSUE THREAD

**Issue by hamsho93** [seanclaude/Redistricting#2]
I installed the plugin from within qgis. I keep getting this message when I click the redistricting icon.

AttributeError: 'module' object has no attribute 'ExtendedInterpolation' 
Traceback (most recent call last):
  File "C:/Users/Administrator/.qgis2/python/plugins\Redistricting\redistricting.py", line 189, in run
    self.dock = RedistrictingDock(self.iface, self.iface.mainWindow())
  File "C:/Users/Administrator/.qgis2/python/plugins\Redistricting\redistricting_dock.py", line 66, in __init__
    Configuration().load()
  File "C:/Users/Administrator/.qgis2/python/plugins\Redistricting\packages\helper\singleton.py", line 6, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "C:/Users/Administrator/.qgis2/python/plugins\Redistricting\configuration.py", line 52, in __init__
    self.__parser = configparser.ConfigParser(interpolation=configparser.ExtendedInterpolation())
AttributeError: 'module' object has no attribute 'ExtendedInterpolation'

Any advice?

**Comment by seanclaude** [comment]
what version of QGIS are you currently using?

**Comment by seanclaude** [comment]
The get it to load, rename the file $HOME/.qgis2/python/plugins/Redistricting/packages/configparser.py to configparser2.py.

And rename all occurrence of configparser to configparser2 in the file $HOME/.qgis2/python/plugins/Redistricting/configuration.py. 

This should get the plugin loading again. Not sure why this is happening now. Maybe because it wasn't tested under linux before. 

Will upload the fix soon.

**Comment by seanclaude** [comment]
Version 0.3.6 is now available in QGIS.
